### ISSUE TITLE
Manchmal wird man nicht automatisch wieder eingeloggt nach einem Timeout

### ISSUE THREAD

**Issue by DevKevYT** [floodoo/SOL-Connect#150]

**Comment by floodoo** [comment]
Ist dieses Ticket noch aktuell?

**Comment by floodoo** [comment]
Hab Login ja neu entwickelt. Eventuell dadurch gefixt

**Comment by DevKevYT** [comment]
Ich glaube das ticket ist alt. Ich habe zumindest heute keine Probleme gehabt. Ich glaube das kann man schließen.
